### ISSUE TITLE
monowall_options.h missing?

### ISSUE THREAD

**Issue by gavinhungry** [blackhole89/compiz-monowall#1]
I'm getting a lot of `undeclared (first use in this function)` when compiling, is there something in the included (but not committed) `monowall_options.h` that I need?

**Comment by blackhole89** [comment]
The header in question is automatically generated (in build/) using the `bcop` script that ships with Compiz 0.8.x; most distributions package it as "compiz-fusion-bcop" (e.g. [here](http://packages.ubuntu.com/search?keywords=compiz-fusion-bcop)) or "compiz-bcop". I believe the makefile is set up to do that assuming the script is present.

**Comment by gavinhungry** [comment]
@blackhole89,

Thanks for the tip. I'm using Arch Linux, `bcop` comes from AUR/compiz-bcop. Got that installed and managed to compile and install your plugin.

Now I'm trying to enable it in CCSM. It auto-disabled Desktop Wall (that's good), but after a second or so, Monowall disabled itself (in CCSM), with nothing written to the console. Any idea what that could be?

**Comment by gavinhungry** [comment]
`"undefined symbol: cairo_xlib_surface_create_with_xrender_format"`

`cairo_xlib_surface_create_with_xrender_format` is defined in `/usr/include/cairo/cairo-xlib-xrender.h` (I had to update your includes to use `include/cairo`):

```
#include <cairo/cairo-xlib-xrender.h>
#include <cairo/cairo.h>
```

**Comment by blackhole89** [comment]
The compiz build system seems to handle additional compiler flags through including `plugin.info` from the makefile, which I had forgotten to add to the repository (fixed now). Thanks for the report; please let me know if it works for you now.

**Comment by gavinhungry** [comment]
Thanks! Compiled correctly and works great now!

I packaged this for the the Arch Linux AUR: https://aur.archlinux.org/packages/compiz-monowall-plugin-git/
