### ISSUE TITLE
make: *** No rule to make target 'build/monowall.lo', needed by 'c-build-objs'.  Stop.

### ISSUE THREAD

**Issue by StefanescuCristian** [blackhole89/compiz-monowall#2]
I'm trying to build on Ubuntu 15.04. 
I cloned the repo, installed missing packages, now when I run `make all` I get the error in the title.

Do you have any idea how to get past that error?

> > > make all
> > > convert   : monowall.xml.in -> build/monowall.xml
> > > bcop'ing  : build/monowall.xml -> build/monowall_options.h
> > > bcop'ing  : build/monowall.xml -> build/monowall_options.c
> > > make: **\* No rule to make target 'build/monowall.lo', needed by 'c-build-objs'.  Stop.

**Comment by blackhole89** [comment]
I don't see why this would be the case yet; it should be covered by one of the `$(BUILDDIR)/%.lo: %.c $(h-files)`-style lines in the Makefile.  You do have monowall.c in the folder you are running `make all` in, yes?

Also, could you perhaps generate and show me the output of `make -d` (particularly anything relevant-looking just before it fails)?

**Comment by StefanescuCristian** [comment]
> > > You do have monowall.c in the folder you are running make all in, yes?
> > > Yes.
> > > 
> > > Also, could you perhaps generate and show me the output of make -d (particularly anything relevant-looking just before it fails)?

Looking for a rule with intermediate file 'monowall.cxx'.
      Avoiding implicit rule recursion.
      Trying pattern rule with stem 'monowall.cxx'.
      Trying implicit prerequisite 'monowall.cxx,v'.
      Trying pattern rule with stem 'monowall.cxx'.
      Trying implicit prerequisite 'RCS/monowall.cxx,v'.
      Trying pattern rule with stem 'monowall.cxx'.
      Trying implicit prerequisite 'RCS/monowall.cxx'.
      Trying pattern rule with stem 'monowall.cxx'.
      Trying implicit prerequisite 's.monowall.cxx'.
      Trying pattern rule with stem 'monowall.cxx'.
      Trying implicit prerequisite 'SCCS/s.monowall.cxx'.
     No implicit rule found for 'build/monowall.lo'.
     Finished prerequisites of target file 'build/monowall.lo'.
    Must remake target 'build/monowall.lo'.
make: **\* No rule to make target 'build/monowall.lo', needed by 'c-build-objs'.  Stop.

Whole log: http://paste.ubuntu.com/11771773/

**Comment by blackhole89** [comment]
Thanks. I think the crucial section of the log is:

> Looking for an implicit rule for 'build/monowall.lo'.
> Trying pattern rule with stem 'monowall'.
> Trying implicit prerequisite 'monowall.c'.
> Trying rule prerequisite 'build/monowall_options.h'.
> Trying rule prerequisite '/usr/include/compiz/compiz.h'.
> Trying pattern rule with stem 'monowall'.

From the looks of it, it gives up because it can't find `/usr/include/compiz/compiz.h`. You might not have Compiz development headers (the package is named compiz-dev on many distros) installed; I should probably list that requirement somewhere.

**Comment by StefanescuCristian** [comment]
I actually have it installed.

┌─[cristi @ ellix] - [/home/cristi/compiz-monowall]
└─[7:47:59]─[>]sagi compiz-dev
[sudo] password for cristi:
Reading package lists... Done
Building dependency tree
Reading state information... Done
compiz-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
┌─[cristi @ ellix] - [/home/cristi/compiz-monowall]
└─[7:51:13]─[>]make
make: **\* No rule to make target 'build/monowall.lo', needed by
'c-build-objs'.  Stop.

There's something strange going on.

On Fri, Jun 26, 2015 at 2:19 AM, Matvey Soloviev notifications@github.com
wrote:

> Thanks. I think the crucial section of the log is:
> Looking for an implicit rule for 'build/monowall.lo'.
> Trying pattern rule with stem 'monowall'.
> Trying implicit prerequisite 'monowall.c'.
> Trying rule prerequisite 'build/monowall_options.h'.
> Trying rule prerequisite '/usr/include/compiz/compiz.h'.
> Trying pattern rule with stem 'monowall'.
> From the looks of it, it gives up because it can't find
> /usr/include/compiz/compiz.h. You might not have Compiz development
> headers (the package is named compiz-dev on many distros) installed; I
> should probably list that requirement somewhere.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/blackhole89/compiz-monowall/issues/2#issuecomment-115428101
> .

## 

Cristian Ștefănescu
https://plus.google.com/+Cristian%C8%98tef%C4%83nescu/about

**Comment by blackhole89** [comment]
Does `/usr/include/compiz/compiz.h` exist? What version of compiz-dev do you have installed (`dpkg -l|grep compiz-dev`)? This plugin is for 0.8.x only, and a cursory inspection does reveal that the 0.9.x compiz-dev package in Ubuntu's repos does not have a header of that name anymore. Also, I think `build/monowall_options.h` should be generated by the bcop compiler... if it is indeed 0.8.x, could you check if that file was created successfully?

**Comment by StefanescuCristian** [comment]
I have installed compiz-dev-0.9.12.1.
Indeed, `/usr/include/compiz/compiz.h` does not exist.

`build/monowall_options.h` is present.

Time to investigate.

**Comment by blackhole89** [comment]
Well, as I said, this plugin won't work with 0.9.x. The 0.9 branch of Compiz is a complete rewrite in C++, so the plugin API is almost entirely different. Since I don't use 0.9, I don't really have the time or motivation to update this plugin to work with it (or, more likely, write a version of it for 0.9 more or less from scratch...), but you are more than welcome to if you want to try it.
